### ISSUE TITLE
🎁 New feature: Add SCSS to the project

### ISSUE THREAD

**Issue by acidbiscuit** [aws-videos-catalog/avc_website#146]
# My Problem

As styling customization demand grows, usage of Bootstrap provided solutions may not be sufficient. Custom styles will quickly get messy unless initial style is definied.

# Solution

Add SCSS preprocessor into the project. Create a short guideline for project styles in a separate file.

**Comment by davidgatti** [comment]
@acidbiscuit I'm not a front-end expert but I'm a back-end developer for the past 20 years, and I don't like adding in a project trendy technologies just because they are popular, because from my experience they just add complexity and remove the simplicity.

How would SCSS make your and others life easier? And what regular CSS is laking here? 

Because this seams to be an extra layer of abstraction that someone needs to know.

**Comment by acidbiscuit** [comment]
@davidgatti 
Adding SCSS to the project is a matter of adding 2 dependencies into the project, since Nuxt.js expects CSS preprocessors to be used.
In the project, the only difference is style syntax with advantage to provide readability, reusability and it also plays great with common CSS methodologies like [BEM](http://getbem.com/), which helps to maintain a certain style of writing styles that plays incredibly well with concern separation of Vue.js components. Thus, planning component architecture and writing styles becomes a single process.  
A person with CSS knowledge will be able to maintain SCSS code. Better yet, having a creative developer without knowledge of any CSS preprocessors may not be a good idea (all of preprocessors are practically the same, with minor syntax difference).

**Comment by davidgatti** [comment]
OK, sounds good, thank you for the clear explanation.
