### ISSUE TITLE
❓ Question: What is the cashing setting

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#155]
# My Question

@acidbiscuit what TTL do we have set on files that we serve? And can we do better than what we have now?

**Comment by acidbiscuit** [comment]
@davidgatti 
We currently do not have cache in the application. Only images are being served from memory cache, which is very short lived.  
We can definitely do better. There are 2 important steps to consider:
1) Add web server configuration to set `Cache-Control` header with expiration.
2) Setup service works on the front-end application to provide efficient caching for all the assets, including app bundles.

**Comment by davidgatti** [comment]
1. Since there is no server this can't be set. THe only way to set a custom TTL for different file would be at upload time to S3. But for that we would need a custom script that while uploading sets the TTL depending on the file type. Maybe Nuxt has something like this? 
2. Sounds reasonable, 

But in any case, we also need to make sure that when we release a new version fo the site the user will get the new page without the need to do. hard refresh or wait for the expiration? If you have a solution please let me know, right now this is the flow:

1. S3 files have no custom header set - we can set any HTTP header on the file.
1. CloudFront reads custom headers set on S3, and forward them to the browser while also listening to those headers itself. So it won't ask the source for the file until the TTL expires
1. When we release a new version, I do tell CloudFront to clear the cash, and pull new data. But in this case the new site will show up for only new users. Since the browser won't make a new request until the TTL expires right?

**Comment by davidgatti** [comment]
I'll wait for your feedback, but I just got a genius idea :D maybe ;)

**Comment by acidbiscuit** [comment]
@davidgatti  
I have different experience when working with S3 and serving app static files.  
1. `CacheControl` header option is respected by S3 when uploading files programmatically and it also can be set via file metadata for already uploaded files/buckets. I am not sure what is the current way of uploading files, but it should be set manually or in file upload client configuration.
2. For Nuxt.js generated files there is no need to flush cache, since all files contain hash value, that is unique to each application build. This covers page and components assets, but does not include static folder (where images are served from). Nuxt.js can set TTL for static folder, but build output files (.js, .css) still should be controlled by the web server. CloudFront seems to allow such configuration: [read article](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html)
