### ISSUE TITLE
🎁 New feature: Make the Ad extend expect on the video page

### ISSUE THREAD

**Issue by davidgatti** [aws-videos-catalog/avc_website#170]
# My Problem

I do like the way the cards extend now to show more content, and I had an idea that the Ads could have a similar feature, but extend on the side to have more content. 

# Solution

When hovering on the ad, extend it to the side of the next card, and take over that space, go over the card. this way we can have more content displayed in the card. A sketch is attached bellow. But don't do this on the video page. Since the video page ad is only a reminder. But it be nice if when you hover on the video add it also popped up like the rest of the cards.

![Screen Shot 2020-10-03 at 9 02 10 AM](https://user-images.githubusercontent.com/411114/94985784-c1685300-0559-11eb-8c38-b1465f07cfe6.png)

**Comment by acidbiscuit** [comment]
@davidgatti Need your input to clarify the task.

I assume we are talking about ads on services listing page (one in the beginning and the end as per #172 ).  
So, while hovering the add, we should extend it to the right (for the first card) and make it as wide as cards gap + next card width, making the ad take 2 cards space. Is it correct?

**Comment by davidgatti** [comment]
You are 100% correct.

**Comment by davidgatti** [comment]
ps, where did you get such a nice dark mode? ;)

**Comment by acidbiscuit** [comment]
There are few cases that add complexity to such implementation:

1) Hover effects are useful only on desktop devices. For services, we show full text without serious layout changes. For ad card we will have to hide additional content or display in underneath the card. 
2) For the ad at the end we will have to display the content to one side or another in case the ad is the first or the last in a row.

Before jumping on the task, I'd like to bring the points about increased complexity, since I have doubts that it solution is worthy in terms of UI/UX. Obviously, I may be missing full picture, so I'd like to ask for your confirmation to start the task.

p.s. Dark mode is ready, but depends on other commits. Will create PRs gradually :)

**Comment by davidgatti** [comment]
OK, decided to skip this altogether for now.
